// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvntWEdEMB5LYtyNZIz-7b-Hf5hOm1o5E',
    appId: '1:706741422863:web:05b689e885939d3eec0c7a',
    messagingSenderId: '706741422863',
    projectId: 'new-app-6627a',
    authDomain: 'new-app-6627a.firebaseapp.com',
    storageBucket: 'new-app-6627a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhz5eike2N_3uWBJt6rSQD_6q0rq1dVMo',
    appId: '1:706741422863:android:6a98d1ec3ac071daec0c7a',
    messagingSenderId: '706741422863',
    projectId: 'new-app-6627a',
    storageBucket: 'new-app-6627a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZe6QeBC-NrYvHSBq1kgP410yg5Jr8azI',
    appId: '1:706741422863:ios:fb63773ffe4da6dcec0c7a',
    messagingSenderId: '706741422863',
    projectId: 'new-app-6627a',
    storageBucket: 'new-app-6627a.appspot.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZe6QeBC-NrYvHSBq1kgP410yg5Jr8azI',
    appId: '1:706741422863:ios:bfc6bb61c6cfd43cec0c7a',
    messagingSenderId: '706741422863',
    projectId: 'new-app-6627a',
    storageBucket: 'new-app-6627a.appspot.com',
    iosBundleId: 'com.example.newApp.RunnerTests',
  );
}
